# Generated by Django 6.0.3 on 2026-03-30 18:25

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='block_details',
            fields=[
                ('block_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('latitude_top_left', models.FloatField(blank=True, null=True)),
                ('longitude_top_left', models.FloatField(blank=True, null=True)),
                ('latitude_bottom_right', models.FloatField(blank=True, null=True)),
                ('longitude_bottom_right', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='meter_details',
            fields=[
                ('meter_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('block_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_backend.block_details')),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('meter_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web_backend.meter_details')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consumption_kw', models.FloatField(default=0.0, help_text='Current energy consumption in kW')),
                ('predicted_kwh', models.FloatField(default=0.0, help_text='Predicted energy consumption for next hour in kWh')),
                ('predicted_kwh_24h', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, help_text='Predicted energy consumption for next 24 hours in kWh', size=24)),
                ('predicted_kwh_week', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, help_text='Predicted energy consumption for next week in kWh', size=168)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_backend.meter_details')),
            ],
        ),
    ]
