# Generated by Django 6.0.3 on 2026-03-30 12:59

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('current_consumption_kw', models.FloatField(default=0.0, help_text='Current energy consumption in kW')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meter_id', models.CharField(help_text='Meter ID associated with this generator data', max_length=50)),
                ('consumption_kw', models.FloatField(default=0.0, help_text='Current energy consumption in kW')),
                ('predicted_kwh', models.FloatField(default=0.0, help_text='Predicted energy consumption for next hour in kWh')),
                ('predicted_kwh_24h', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, help_text='Predicted energy consumption for next 24 hours in kWh', size=24)),
                ('predicted_kwh_week', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, help_text='Predicted energy consumption for next week in kWh', size=168)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratorModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cons_id', models.IntegerField(help_text='Consumer ID from mobile app')),
                ('data_time', models.DateTimeField(auto_now_add=True, unique=True)),
                ('active_import', models.FloatField(default=0.0, help_text='Active import in kW')),
                ('active_export', models.FloatField(default=0.0, help_text='Active export in kW')),
                ('reactive_import', models.FloatField(default=0.0, help_text='Reactive import in kVAR')),
                ('reactive_export', models.FloatField(default=0.0, help_text='Reactive export in kVAR')),
                ('apparant_import', models.FloatField(default=0.0, help_text='Apparent import in kVA')),
                ('apparant_export', models.FloatField(default=0.0, help_text='Apparent export in kVA')),
                ('active_power', models.FloatField(default=0.0, help_text='Active power in kW')),
                ('meter_id', models.CharField(help_text='Meter ID associated with this reading', max_length=50)),
                ('hourly_khw', models.FloatField(default=0.0, help_text='Hourly energy consumption in kWh')),
                ('predicted_kwh', models.FloatField(default=0.0, help_text='Predicted energy consumption for next hour in kWh')),
                ('source', models.CharField(default='base')),
            ],
        ),
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('substation_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=225)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeterID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_backend.generator')),
            ],
        ),
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('transformer_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('capacity_kw', models.FloatField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformers', to='web_backend.substation')),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=50, unique=True)),
                ('consumer_id', models.IntegerField(blank=True, help_text='Consumer ID from source system', null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('prediction_hour_1_kw', models.FloatField(default=0, help_text='Predicted consumption 1 hour from now')),
                ('prediction_hour_2_kw', models.FloatField(default=0, help_text='Predicted consumption 2 hours from now')),
                ('prediction_hour_3_kw', models.FloatField(default=0, help_text='Predicted consumption 3 hours from now')),
                ('prediction_hour_4_kw', models.FloatField(default=0, help_text='Predicted consumption 4 hours from now')),
                ('prediction_hour_5_kw', models.FloatField(default=0, help_text='Predicted consumption 5 hours from now')),
                ('prediction_hour_6_kw', models.FloatField(default=0, help_text='Predicted consumption 6 hours from now')),
                ('prediction_next_day_kwh', models.FloatField(default=0, help_text='Predicted total consumption for next 24 hours in kwh')),
                ('prediction_next_week_kwh', models.FloatField(default=0, help_text='Predicted total comsuption for next 7 days in kwh')),
                ('prediction_next_month_kwh', models.FloatField(default=0, help_text='Predicted total consumption for next month in kwh')),
                ('prediction_next_year_kwh', models.FloatField(default=0, help_text='Predicted total consumption for next year in kwh')),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_backend.transformer')),
            ],
        ),
        migrations.CreateModel(
            name='TransformerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_kw', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_backend.transformer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
