# Generated by Django 5.2.11 on 2026-02-13 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('current_consumption_kw', models.FloatField(default=0.0, help_text='Current energy consumption in kW')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TransformerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_kw', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tronsformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_backend.transformer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
