# Generated by Django 6.0.3 on 2026-03-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='meter_details',
            fields=[
                ('meter_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('meter_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
    ]
