# Generated by Django 6.0.3 on 2026-03-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_backend', '0002_meter_details_user_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='block_details',
            fields=[
                ('block_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('latitude_top_left', models.FloatField(blank=True, null=True)),
                ('longitude_top_left', models.FloatField(blank=True, null=True)),
                ('latitude_bottom_right', models.FloatField(blank=True, null=True)),
                ('longitude_bottom_right', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='meter_details',
            name='block_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
