# Generated by Django 5.2.11 on 2026-02-16 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_backend', '0002_energyreading_transformerreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=50, unique=True)),
                ('consumer_id', models.IntegerField(blank=True, help_text='Consumer ID from source system', null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('prediction_hour_1_kw', models.FloatField(default=0, help_text='Predicted consumption 1 hour from now')),
                ('prediction_hour_2_kw', models.FloatField(default=0, help_text='Predicted consumption 2 hours from now')),
                ('prediction_hour_3_kw', models.FloatField(default=0, help_text='Predicted consumption 3 hours from now')),
                ('prediction_hour_4_kw', models.FloatField(default=0, help_text='Predicted consumption 4 hours from now')),
                ('prediction_hour_5_kw', models.FloatField(default=0, help_text='Predicted consumption 5 hours from now')),
                ('prediction_hour_6_kw', models.FloatField(default=0, help_text='Predicted consumption 6 hours from now')),
                ('prediction_next_day_kwh', models.FloatField(default=0, help_text='Predicted total consumption for next 24 hours in kwh')),
                ('prediction_next_week_kwh', models.FloatField(default=0, help_text='Predicted total comsuption for next 7 days in kwh')),
                ('prediction_next_month_kwh', models.FloatField(default=0, help_text='Predicted total consumption for next month in kwh')),
                ('prediction_next_year_kwh', models.FloatField(default=0, help_text='Predicted total consumption for next year in kwh')),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_backend.transformer')),
            ],
        ),
    ]
