# Generated by Django 5.2.11 on 2026-02-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_backend', '0003_meter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transformerreading',
            old_name='tronsformer',
            new_name='transformer',
        ),
    ]
