# Generated by Django 6.0.3 on 2026-03-30 10:06

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_backend', '0004_rename_tronsformer_transformerreading_transformer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('meter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('consumption_kw', models.FloatField(default=0.0, help_text='Current energy consumption in kW')),
                ('predicted_kwh', models.FloatField(default=0.0, help_text='Predicted energy consumption for next hour in kWh')),
                ('predicted_kwh_24h', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, help_text='Predicted energy consumption for next 24 hours in kWh', size=24)),
                ('predicted_kwh_week', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, help_text='Predicted energy consumption for next week in kWh', size=168)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratorModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cons_id', models.IntegerField(help_text='Consumer ID from mobile app')),
                ('data_time', models.DateTimeField(auto_now_add=True, unique=True)),
                ('active_import', models.FloatField(default=0.0, help_text='Active import in kW')),
                ('active_export', models.FloatField(default=0.0, help_text='Active export in kW')),
                ('reactive_import', models.FloatField(default=0.0, help_text='Reactive import in kVAR')),
                ('reactive_export', models.FloatField(default=0.0, help_text='Reactive export in kVAR')),
                ('apparant_import', models.FloatField(default=0.0, help_text='Apparent import in kVA')),
                ('apparant_export', models.FloatField(default=0.0, help_text='Apparent export in kVA')),
                ('active_power', models.FloatField(default=0.0, help_text='Active power in kW')),
                ('meter_id', models.CharField(help_text='Meter ID associated with this reading', max_length=50)),
                ('hourly_khw', models.FloatField(default=0.0, help_text='Hourly energy consumption in kWh')),
                ('predicted_kwh', models.FloatField(default=0.0, help_text='Predicted energy consumption for next hour in kWh')),
                ('source', models.CharField(default='base')),
            ],
        ),
        migrations.CreateModel(
            name='MeterID',
            fields=[
                ('cons_id', models.AutoField(help_text='Consumer ID from mobile app', primary_key=True, serialize=False)),
                ('meter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_backend.generator')),
            ],
        ),
    ]
