# Generated by Django 6.0.3 on 2026-03-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_backend', '0005_generator_generatormodel_meterid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='meter_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
