# Generated by Django 6.0.3 on 2026-03-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_backend', '0006_alter_generator_meter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generator',
            name='meter_id',
            field=models.CharField(help_text='Meter ID associated with this generator data', max_length=50, primary_key=True, serialize=False),
        ),
    ]
